// File generated by FlutterFire CLI.
// Replace with actual configuration from:
//   flutterfire configure
//
// To regenerate, run:
//   flutterfire configure --project=<your-project-id>

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.windows:
        return web; // Use web config for Windows desktop
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // ── FIREBASE CONFIG ──

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDfxy4yxBxsvv9Nyoj96YbS-0ZcBNZcENU',
    appId: '1:724978588214:web:5e7dcd950c6be4d35b1697',
    messagingSenderId: '724978588214',
    projectId: 'maratech-a2850',
    storageBucket: 'maratech-a2850.firebasestorage.app',
    authDomain: 'maratech-a2850.firebaseapp.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDfxy4yxBxsvv9Nyoj96YbS-0ZcBNZcENU',
    appId: '1:724978588214:android:807fdd023e2cb5e85b1697',
    messagingSenderId: '724978588214',
    projectId: 'maratech-a2850',
    storageBucket: 'maratech-a2850.firebasestorage.app',
  );

  // Run: flutterfire configure

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBY8fFVSwu5n1MPyTVEd2g-yGjpKBJxdZw',
    appId: '1:724978588214:ios:c801e923b29ab8045b1697',
    messagingSenderId: '724978588214',
    projectId: 'maratech-a2850',
    storageBucket: 'maratech-a2850.firebasestorage.app',
    iosBundleId: 'running.club.app',
  );

}